### ISSUE TITLE
Site deployment error.

### ISSUE THREAD

**Issue by skgupta507** [avalynndev/enjoytown#10]
hey @avalynndev i was unable to deploy the website cause i got these errors.
these errors are caused due a missing variables in the env file. which is not present in the repo. can u share the env template and where to get the api keys from.
it would be a great help.
or if its a different issue kindly let me know how to fix that.

Collecting page data ...
--
23:19:10.535 | ❌ Invalid environment variables: { DOWNLOAD_API_URL: [ 'Required' ], API_KEY: [ 'Required' ] }
23:19:10.536 | Error: Invalid environment variables
23:19:10.536 | at p (/vercel/path0/.next/server/chunks/671.js:46:9393)
23:19:10.536 | at i (/vercel/path0/.next/server/chunks/671.js:46:9573)
23:19:10.536 | at i (/vercel/path0/.next/server/chunks/671.js:46:11039)
23:19:10.536 | at 73066 (/vercel/path0/.next/server/app/kdrama/info/[id]/page.js:1:15508)
23:19:10.536 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
23:19:10.536 | at 30532 (/vercel/path0/.next/server/app/kdrama/info/[id]/page.js:1:13307)
23:19:10.536 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
23:19:10.536 | at 24194 (/vercel/path0/.next/server/app/kdrama/info/[id]/page.js:1:5989)
23:19:10.536 | at t (/vercel/path0/.next/server/webpack-runtime.js:1:127)
23:19:10.536 | at 35698 (/vercel/path0/.next/server/app/kdrama/info/[id]/page.js:1:948)
23:19:10.538 |  
23:19:10.538 | > Build error occurred
23:19:10.541 | Error: Failed to collect page data for /kdrama/info/[id]
23:19:10.541 | at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
23:19:10.541 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
23:19:10.541 | type: 'Error'
23:19:10.541 | }
23:19:10.625 | Error: Command "npm run build" exited with 1

**Comment by avalynndev** [comment]
atm there is a error with that stuff, so after i fix it il tell ya

**Comment by avalynndev** [comment]
update your forked repo and the env template is:

```env
DOWNLOAD_API_URL=https://v1.api.ani.rohi.dev/api/dramacool
```
