### ISSUE TITLE
[Bug]: issue deploying

### ISSUE THREAD

**Issue by avalynndev** [avalynndev/enjoytown#143]
### What went wrong?

not able to deploy the website to netlify for some reason

### How'd you stumble upon it?

just deploy to netlify ul get the same problem 0-0

### What you hoped for vs. What actually happened

expected to work but doesn't fetch data 0-0

### Which browsers were a bummer?

Firefox, Chrome, Safari, Microsoft Edge

### Got logs?

```shell
6:55:00 AM: Error: Failed to fetch data
6:55:00 AM:     at u (/opt/build/repo/.next/server/app/tv/page.js:1:22075)
6:55:00 AM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
6:55:00 AM:     at async i (/opt/build/repo/.next/server/chunks/6170.js:1:185)
6:55:00 AM: Error: Failed to fetch data
6:55:00 AM:     at u (/opt/build/repo/.next/server/app/tv/page.js:1:22075)
6:55:00 AM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
6:55:00 AM:     at async i (/opt/build/repo/.next/server/chunks/6170.js:1:185)
6:55:00 AM: Error: Failed to fetch data
6:55:00 AM:     at m (/opt/build/repo/.next/server/app/movie/page.js:1:25876)
6:55:00 AM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
6:55:00 AM:     at async l (/opt/build/repo/.next/server/chunks/359.js:1:183)
6:55:00 AM: Error: Failed to fetch data
6:55:00 AM:     at m (/opt/build/repo/.next/server/app/movie/page.js:1:25876)
6:55:00 AM:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
6:55:00 AM:     at async l (/opt/build/repo/.next/server/chunks/359.js:1:183)
6:55:00 AM:    Generating static pages (7/15)
6:55:00 AM:    Generating static pages (11/15)
6:55:00 AM:  ✓ Generating static pages (15/15)
6:55:00 AM: > Export encountered errors on following paths:
6:55:00 AM: 	/tv/page: /tv
```

### Code of Conduct Agreement

- [X] I agree to follow this project's Code of Conduct.

**Comment by avalynndev** [comment]
This error is caused as the Proxy URL is wrong.. and theres another problem.. nextjs cache is disabled
```
7:22:11 AM: ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
```

**Comment by avalynndev** [comment]
fixed
